### ISSUE TITLE
HIPAA technical details page: add app and infra "Details" sections

### ISSUE THREAD

**Issue by zackproser** [gruntwork-io/gruntwork-io.github.io#474]
The zig zag portion is a bit short. See [this comment](https://github.com/gruntwork-io/gruntwork-io.github.io/pull/456#discussion_r673986479) for ideas on a few more zigs/zags and more info to put below that.

**Comment by ebeneliason** [comment]
Related — we should probably fix the height of the code window and have it scroll as needed so that a) it doesn't cause re-layout when changing tabs and b) it doesn't push the rest of the page content way down. Maybe a fixed height of `450px` or so?

The one gotcha I see here is that the little red label from the figure is inside the element which will need to scroll, so we may need to hide it, shift it fully inside its container (which will need `overflow: scroll`), or use another element in its parent instead.
